/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as EndpointRouteImport } from './routes/endpoint'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProxyPoolsRouteImport } from './routes/proxy-pools'
import { Route as UsageRouteImport } from './routes/usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointRoute = EndpointRouteImport.update({
  id: '/endpoint',
  path: '/endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyPoolsRoute = ProxyPoolsRouteImport.update({
  id: '/proxy-pools',
  path: '/proxy-pools',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/endpoint': typeof EndpointRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/proxy-pools': typeof ProxyPoolsRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/endpoint': typeof EndpointRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/proxy-pools': typeof ProxyPoolsRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/endpoint': typeof EndpointRoute
  '/playground': typeof PlaygroundRoute
  '/providers': typeof ProvidersRoute
  '/proxy-pools': typeof ProxyPoolsRoute
  '/usage': typeof UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combos'
    | '/endpoint'
    | '/playground'
    | '/providers'
    | '/proxy-pools'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combos'
    | '/endpoint'
    | '/playground'
    | '/providers'
    | '/proxy-pools'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/combos'
    | '/endpoint'
    | '/playground'
    | '/providers'
    | '/proxy-pools'
    | '/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombosRoute: typeof CombosRoute
  EndpointRoute: typeof EndpointRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProvidersRoute: typeof ProvidersRoute
  ProxyPoolsRoute: typeof ProxyPoolsRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint': {
      id: '/endpoint'
      path: '/endpoint'
      fullPath: '/endpoint'
      preLoaderRoute: typeof EndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy-pools': {
      id: '/proxy-pools'
      path: '/proxy-pools'
      fullPath: '/proxy-pools'
      preLoaderRoute: typeof ProxyPoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombosRoute: CombosRoute,
  EndpointRoute: EndpointRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProvidersRoute: ProvidersRoute,
  ProxyPoolsRoute: ProxyPoolsRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
